version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: eussi-db
    restart: always
    environment:
      POSTGRES_USER: eussi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: issue
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: